/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ICECandidate = IDL.Text;
export const SDP = IDL.Text;

export const idlService = IDL.Service({
  'addIceCandidate' : IDL.Func([IDL.Text, ICECandidate, IDL.Bool], [], []),
  'getGuestAnswer' : IDL.Func([IDL.Text], [IDL.Opt(SDP)], ['query']),
  'getGuestIceCandidates' : IDL.Func([IDL.Text], [IDL.Vec(ICECandidate)], []),
  'getHostIceCandidates' : IDL.Func([IDL.Text], [IDL.Vec(ICECandidate)], []),
  'getHostOffer' : IDL.Func([IDL.Text], [IDL.Opt(SDP)], ['query']),
  'guestAnswer' : IDL.Func([IDL.Text, SDP], [], []),
  'hostOffer' : IDL.Func([IDL.Text, SDP], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ICECandidate = IDL.Text;
  const SDP = IDL.Text;
  
  return IDL.Service({
    'addIceCandidate' : IDL.Func([IDL.Text, ICECandidate, IDL.Bool], [], []),
    'getGuestAnswer' : IDL.Func([IDL.Text], [IDL.Opt(SDP)], ['query']),
    'getGuestIceCandidates' : IDL.Func([IDL.Text], [IDL.Vec(ICECandidate)], []),
    'getHostIceCandidates' : IDL.Func([IDL.Text], [IDL.Vec(ICECandidate)], []),
    'getHostOffer' : IDL.Func([IDL.Text], [IDL.Opt(SDP)], ['query']),
    'guestAnswer' : IDL.Func([IDL.Text, SDP], [], []),
    'hostOffer' : IDL.Func([IDL.Text, SDP], [], []),
  });
};

export const init = ({ IDL }) => { return []; };